language: python
python: 
- 3.6

install:
- pip install nbconvert

script:
- jupyter nbconvert *.ipynb
- ls **

deploy:
  local_dir: .
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
